project:
  type: website
  output-dir: docs

website:
  title: "Ethan Elasky"
  favicon: favicon.ico
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: index.qmd
        text: Blog
      - icon: github
        href: https://github.com/ethanelasky
      - icon: twitter
        href: https://twitter.com/elaskyethan

format:
  html:
    theme: 
      - styles.scss
      - flatly
    toc: true
    mainfont: "EB Garamond"